version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pgdev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432
  appl:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/cal
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
